version: '3.1'

services:

  web:
    build:
      context: '.'
      dockerfile: '.Dockerfile'
    restart: always
    volumes:
      - ./:/app
    networks:
      pusa:
    ports:
      - 5000:5000
    command: yarn && yarn start

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      pusa:
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    networks:
      pusa:
    ports:
      - 8080:8080

networks:
  pusa:
