version: '3.1'

services:
  pusa:
    networks:
      pusa-net:
  db:
    image: mariadb
    restart: always
    networks:
      pusa-net:
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - dbPusa:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    networks:
      pusa-net:
    ports:
      - 8080:8080

volumes:
  dbPusa:
networks:
  pusa-net:

